import { AppState, User, RepairSupplier } from '@/types'

const initialUsers: User[] = [
  {
    id: 'u1',
    name: 'Administrador Master',
    email: 'admin@estoque.pro',
    role: 'Gestor',
    active: true,
  },
  {
    id: 'u2',
    name: 'Carlos (Líder Tacha 1)',
    email: 'carlos@estoque.pro',
    role: 'Encarregado',
    teamId: 't1',
    active: true,
  },
  {
    id: 'u3',
    name: 'João (Operador Tacha 1)',
    email: 'joao@estoque.pro',
    role: 'Analista',
    teamId: 't1',
    active: true,
  },
  {
    id: 'u4',
    name: 'Ana (Líder Alpha)',
    email: 'ana@estoque.pro',
    role: 'Encarregado Gestor',
    teamId: 't2',
    active: true,
  },
  {
    id: 'u5',
    name: 'Visitante (Consulta)',
    email: 'visitante@estoque.pro',
    role: 'Visualizador',
    active: true,
  },
]

const initialNodes = [
  { id: 'd1', name: 'Ferramentas Elétricas', level: 'departamento', parentId: null },
  { id: 'd2', name: 'Ferramentas Manuais', level: 'departamento', parentId: null },
  { id: 'c1', name: 'Furadeiras e Parafusadeiras', level: 'categoria', parentId: 'd1' },
  { id: 'c2', name: 'Chaves', level: 'categoria', parentId: 'd2' },
  { id: 'c3', name: 'Sinalização', level: 'categoria', parentId: 'd2' },
  { id: 'tp1', name: 'Bateria', level: 'tipo', parentId: 'c1' },
  { id: 'tp2', name: 'Phillips', level: 'tipo', parentId: 'c2' },
  { id: 'tp3', name: 'Cone', level: 'tipo', parentId: 'c3' },
  { id: 'ln1', name: 'Impacto 12V', level: 'linha', parentId: 'tp1' },
  { id: 'ln2', name: 'Manual', level: 'linha', parentId: 'tp2' },
  { id: 'ln3', name: 'Plástico', level: 'linha', parentId: 'tp3' },
  { id: 'm1', name: 'Makita', level: 'marca', parentId: 'ln1' },
  { id: 'm3', name: 'Tramontina', level: 'marca', parentId: 'ln2' },
  { id: 'm4', name: 'Plastcor', level: 'marca', parentId: 'ln3', isGrouped: true },
] as const

const initialTeams = [
  { id: 't1', name: 'Equipe Tacha 1', description: 'Manutenção Externa', location: 'Setor Norte' },
  { id: 't2', name: 'Equipe Alpha', description: 'Reparos Rápidos', location: 'Setor Sul' },
] as const

const initialSuppliers: RepairSupplier[] = [
  {
    id: 's1',
    name: 'Assistência Técnica Oficial',
    cnpj: '12.345.678/0001-90',
    currentBalance: 5000,
  },
  { id: 's2', name: 'Reparos Express', cnpj: '98.765.432/0001-10', currentBalance: 2500 },
]

const initialInventory = [
  {
    id: 'inv1',
    hasAssetNumber: true,
    assetNumber: 'PAT-10001',
    teamId: 't1',
    treeNodeId: 'm1',
    condition: 'good',
    status: 'present',
    photos: [
      'https://img.usecurling.com/p/400/400?q=drill&seed=1',
      'https://img.usecurling.com/p/400/400?q=drill&seed=2',
    ],
    lastUpdated: new Date().toISOString(),
    price: 450.0,
    quantity: 1,
  },
  {
    id: 'inv2',
    hasAssetNumber: true,
    assetNumber: 'PAT-10002',
    teamId: 't1',
    treeNodeId: 'm3',
    condition: 'damaged',
    status: 'borrowed',
    borrowedTo: 'Equipe Beta',
    photos: ['https://img.usecurling.com/p/400/400?q=screwdriver'],
    lastUpdated: new Date().toISOString(),
    price: 85.5,
    damagedDate: new Date(Date.now() - 43200000).toISOString(),
    damagedUser: 'Carlos (Líder Tacha 1)',
    quantity: 1,
    conditionCategory: 'Danificado com chance de reparo',
  },
  {
    id: 'inv3',
    hasAssetNumber: false,
    teamId: 't2',
    treeNodeId: 'm1',
    condition: 'good',
    status: 'present',
    photos: ['https://img.usecurling.com/p/400/400?q=power%20tool'],
    lastUpdated: new Date().toISOString(),
    price: 320.0,
    quantity: 1,
  },
  {
    id: 'inv4',
    hasAssetNumber: true,
    assetNumber: 'PAT-10004',
    teamId: 't2',
    treeNodeId: 'm1',
    condition: 'repair',
    status: 'in_maintenance',
    photos: ['https://img.usecurling.com/p/400/400?q=tool%20repair&seed=5'],
    lastUpdated: new Date().toISOString(),
    price: 520.0,
    repairCost: 150.0,
    supplierId: 's1',
    repairLocation: 'Assistência Técnica Oficial',
    repairDescription: 'Troca de escovas e lubrificação do motor',
    repairUser: 'Ana (Líder Alpha)',
    repairDate: new Date(Date.now() - 86400000).toISOString(),
    quantity: 1,
    repairSent: true,
    expectedReturnDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    conditionCategory: 'Itens com reparo alto',
  },
  {
    id: 'inv5',
    hasAssetNumber: false,
    teamId: 't1',
    treeNodeId: 'm4',
    condition: 'good',
    status: 'present',
    photos: [],
    lastUpdated: new Date().toISOString(),
    price: 45.0,
    quantity: 230,
  },
] as const

export const initialData: AppState = {
  users: initialUsers,
  currentUser: null,
  nodes: [...initialNodes] as any,
  teams: [...initialTeams],
  inventory: [...initialInventory] as any,
  transfers: [
    {
      id: 'tr1',
      inventoryId: 'inv3',
      fromTeamId: 't2',
      toTeamId: 't1',
      initiatedBy: 'Ana (Líder Alpha)',
      initiatedAt: new Date().toISOString(),
      status: 'pending',
    },
  ],
  activities: [],
  history: [
    {
      id: 'h1',
      inventoryId: 'inv1',
      date: new Date(Date.now() - 86400000).toISOString(),
      type: 'allocation',
      description: 'Alocado inicialmente para a Equipe Tacha 1.',
      user: 'Sistema',
    },
    {
      id: 'h2',
      inventoryId: 'inv2',
      date: new Date(Date.now() - 43200000).toISOString(),
      type: 'status_change',
      description:
        'Condição alterada para damaged. Motivo: Ponta gasta pelo uso em superfícies duras.',
      user: 'Carlos (Líder Tacha 1)',
    },
    {
      id: 'h3',
      inventoryId: 'inv4',
      date: new Date(Date.now() - 86400000).toISOString(),
      type: 'status_change',
      description:
        'Condição alterada para repair. Local: Assistência Técnica Oficial. Custo: R$150.',
      user: 'Ana (Líder Alpha)',
    },
    {
      id: 'h4',
      inventoryId: 'inv5',
      date: new Date(Date.now() - 86400000).toISOString(),
      type: 'allocation',
      description: 'Alocado lote inicial de sinalização.',
      user: 'Sistema',
    },
  ],
  checklists: [],
  suppliers: initialSuppliers,
}
