DO $$
DECLARE
  admin_id UUID := gen_random_uuid();
  team_manutencao_id TEXT := 't_manutencao';
  team_logistica_id TEXT := 't_logistica';
  team_admin_id TEXT := 't_admin';
  
  -- Nodes
  dep_ferramentas TEXT := 'n_dep_ferr';
  dep_ti TEXT := 'n_dep_ti';
  dep_mobil TEXT := 'n_dep_mobil';
  
  sec_ferr_ele TEXT := 'n_sec_ferr_ele';
  sec_ti_hard TEXT := 'n_sec_ti_hard';
  sec_mobil_esc TEXT := 'n_sec_mobil_esc';
  
  cat_furadeira TEXT := 'n_cat_furadeira';
  cat_serra TEXT := 'n_cat_serra';
  cat_laptop TEXT := 'n_cat_laptop';
  cat_monitor TEXT := 'n_cat_monitor';
  cat_cadeira TEXT := 'n_cat_cadeira';
  
  -- Items
  it_furadeira_imp TEXT := 'n_it_furadeira_imp';
  it_serra_cir TEXT := 'n_it_serra_cir';
  it_laptop_dev TEXT := 'n_it_laptop_dev';
  it_monitor_24 TEXT := 'n_it_monitor_24';
  it_cadeira_erg TEXT := 'n_it_cadeira_erg';
  
  -- Marcas
  ma_makita TEXT := 'n_ma_makita';
  ma_bosch TEXT := 'n_ma_bosch';
  ma_dell TEXT := 'n_ma_dell';
  ma_lg TEXT := 'n_ma_lg';
  ma_flex TEXT := 'n_ma_flex';
  
BEGIN

  -- 1. Create Master Admin
  INSERT INTO auth.users (
    id, instance_id, email, encrypted_password, email_confirmed_at,
    created_at, updated_at, raw_app_meta_data, raw_user_meta_data,
    is_super_admin, role, aud,
    confirmation_token, recovery_token, email_change_token_new,
    email_change, email_change_token_current,
    phone, phone_change, phone_change_token, reauthentication_token
  ) VALUES (
    admin_id,
    '00000000-0000-0000-0000-000000000000',
    'admin@gestao.com',
    crypt('Admin123!', gen_salt('bf')),
    NOW(), NOW(), NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"full_name": "Administrador Master"}',
    false, 'authenticated', 'authenticated',
    '', '', '', '', '',
    NULL,
    '', '', ''
  );

  -- Update the profile that was auto-generated by the trigger
  UPDATE public.profiles
  SET role = 'Gestor',
      full_name = 'Administrador Master',
      is_active = true
  WHERE id = admin_id;

  -- 2. Create Teams
  INSERT INTO teams (id, name, description, location) VALUES 
  (team_manutencao_id, 'Manutenção Industrial', 'Equipe responsável pela manutenção da planta', 'Galpão 1'),
  (team_logistica_id, 'Operações Logísticas', 'Equipe de movimentação e armazenagem', 'Armazém Central'),
  (team_admin_id, 'Administrativo', 'Gestão e suporte', 'Prédio Principal')
  ON CONFLICT (id) DO NOTHING;

  -- 3. Create Nodes (Tree)
  INSERT INTO nodes (id, name, level, parent_id, is_grouped) VALUES
  (dep_ferramentas, 'Ferramentas', 'departamento', null, false),
  (dep_ti, 'Equipamentos de TI', 'departamento', null, false),
  (dep_mobil, 'Mobiliário', 'departamento', null, false),
  
  (sec_ferr_ele, 'Ferramentas Elétricas', 'secao', dep_ferramentas, false),
  (sec_ti_hard, 'Hardware', 'secao', dep_ti, false),
  (sec_mobil_esc, 'Escritório', 'secao', dep_mobil, false),
  
  (cat_furadeira, 'Furadeiras', 'categoria', sec_ferr_ele, false),
  (cat_serra, 'Serras', 'categoria', sec_ferr_ele, false),
  (cat_laptop, 'Laptops', 'categoria', sec_ti_hard, false),
  (cat_monitor, 'Monitores', 'categoria', sec_ti_hard, false),
  (cat_cadeira, 'Cadeiras Ergonômicas', 'categoria', sec_mobil_esc, false),
  
  (it_furadeira_imp, 'Furadeira de Impacto', 'item', cat_furadeira, false),
  (it_serra_cir, 'Serra Circular', 'item', cat_serra, false),
  (it_laptop_dev, 'Laptop Developer', 'item', cat_laptop, false),
  (it_monitor_24, 'Monitor 24"', 'item', cat_monitor, false),
  (it_cadeira_erg, 'Cadeira Erg.', 'item', cat_cadeira, false),
  
  (ma_makita, 'Makita', 'marca', it_furadeira_imp, false),
  (ma_bosch, 'Bosch', 'marca', it_serra_cir, false),
  (ma_dell, 'Dell', 'marca', it_laptop_dev, false),
  (ma_lg, 'LG', 'marca', it_monitor_24, false),
  (ma_flex, 'Flexform', 'marca', it_cadeira_erg, true)
  ON CONFLICT (id) DO NOTHING;

  -- 4. Assets
  FOR i IN 1..10 LOOP
    INSERT INTO assets (
      id, departamento, secao, categoria, item, marca, tree_node_id, 
      patrimony_number, is_batch, current_quantity, team_id, condition, status, price, photos
    ) VALUES (
      'a_fur_' || i, 'Ferramentas', 'Ferramentas Elétricas', 'Furadeiras', 'Furadeira de Impacto', 'Makita', ma_makita,
      'PAT-FUR-' || LPAD(i::text, 4, '0'), false, 1, team_manutencao_id, 
      CASE WHEN i % 5 = 0 THEN 'damaged' WHEN i % 4 = 0 THEN 'repair' ELSE 'good' END, 
      CASE WHEN i % 5 = 0 THEN 'missing' WHEN i % 4 = 0 THEN 'in_maintenance' ELSE 'present' END, 
      450.00,
      '["https://img.usecurling.com/p/400/400?q=drill"]'::jsonb
    ) ON CONFLICT (id) DO NOTHING;
  END LOOP;

  FOR i IN 1..5 LOOP
    INSERT INTO assets (
      id, departamento, secao, categoria, item, marca, tree_node_id, 
      patrimony_number, is_batch, current_quantity, team_id, condition, status, price, photos
    ) VALUES (
      'a_ser_' || i, 'Ferramentas', 'Ferramentas Elétricas', 'Serras', 'Serra Circular', 'Bosch', ma_bosch,
      'PAT-SER-' || LPAD(i::text, 4, '0'), false, 1, team_manutencao_id, 
      'good', 'present', 850.00,
      '["https://img.usecurling.com/p/400/400?q=saw"]'::jsonb
    ) ON CONFLICT (id) DO NOTHING;
  END LOOP;

  FOR i IN 1..8 LOOP
    INSERT INTO assets (
      id, departamento, secao, categoria, item, marca, tree_node_id, 
      patrimony_number, is_batch, current_quantity, team_id, condition, status, price, photos
    ) VALUES (
      'a_lap_' || i, 'Equipamentos de TI', 'Hardware', 'Laptops', 'Laptop Developer', 'Dell', ma_dell,
      'PAT-LAP-' || LPAD(i::text, 4, '0'), false, 1, team_admin_id, 
      CASE WHEN i = 8 THEN 'repair' ELSE 'good' END, 
      CASE WHEN i = 8 THEN 'in_maintenance' ELSE 'present' END, 
      4500.00,
      '["https://img.usecurling.com/p/400/400?q=laptop"]'::jsonb
    ) ON CONFLICT (id) DO NOTHING;
  END LOOP;

  FOR i IN 1..5 LOOP
    INSERT INTO assets (
      id, departamento, secao, categoria, item, marca, tree_node_id, 
      patrimony_number, is_batch, current_quantity, team_id, condition, status, price, photos
    ) VALUES (
      'a_mon_' || i, 'Equipamentos de TI', 'Hardware', 'Monitores', 'Monitor 24"', 'LG', ma_lg,
      'PAT-MON-' || LPAD(i::text, 4, '0'), false, 1, team_admin_id, 
      'good', 'present', 900.00,
      '["https://img.usecurling.com/p/400/400?q=monitor"]'::jsonb
    ) ON CONFLICT (id) DO NOTHING;
  END LOOP;

  INSERT INTO assets (
    id, departamento, secao, categoria, item, marca, tree_node_id, 
    patrimony_number, is_batch, current_quantity, team_id, condition, status, price, photos
  ) VALUES (
    'a_cad_1', 'Mobiliário', 'Escritório', 'Cadeiras Ergonômicas', 'Cadeira Erg.', 'Flexform', ma_flex,
    NULL, true, 25, team_admin_id, 'good', 'present', 600.00, '["https://img.usecurling.com/p/400/400?q=office%20chair"]'::jsonb
  ),
  (
    'a_cad_2', 'Mobiliário', 'Escritório', 'Cadeiras Ergonômicas', 'Cadeira Erg.', 'Flexform', ma_flex,
    NULL, true, 10, team_logistica_id, 'good', 'present', 600.00, '["https://img.usecurling.com/p/400/400?q=office%20chair"]'::jsonb
  ) ON CONFLICT (id) DO NOTHING;

  -- 5. Repairs (10 records)
  INSERT INTO repairs (id, asset_id, is_sent, estimated_completion_date, condition_status, cost, location, description, repair_user, repair_date) VALUES 
  (gen_random_uuid()::text, 'a_fur_4', true, NOW() + INTERVAL '5 days', 'Itens com reparo alto', 150.00, 'Assistência Externa', 'Troca de motor', 'Carlos Silva', NOW() - INTERVAL '2 days'),
  (gen_random_uuid()::text, 'a_fur_8', false, NOW() + INTERVAL '2 days', 'Itens com reparo baixo', 45.00, 'Oficina Interna', 'Limpeza e lubrificação', 'João Santos', NOW() - INTERVAL '1 day'),
  (gen_random_uuid()::text, 'a_lap_8', true, NOW() + INTERVAL '10 days', 'Danificado com chance de reparo', 800.00, 'Dell Assistência', 'Troca de placa mãe', 'Maria Admin', NOW() - INTERVAL '5 days'),
  (gen_random_uuid()::text, 'a_ser_2', true, NOW() - INTERVAL '1 day', 'Reparado', 120.00, 'Assistência Externa', 'Troca de disco', 'Carlos Silva', NOW() - INTERVAL '10 days'),
  (gen_random_uuid()::text, 'a_mon_2', true, NOW() + INTERVAL '7 days', 'Danificado com chance de reparo', 300.00, 'Assistência LG', 'Reparo na fonte', 'Maria Admin', NOW() - INTERVAL '3 days'),
  (gen_random_uuid()::text, 'a_fur_2', false, NOW() + INTERVAL '1 day', 'Itens com reparo baixo', 30.00, 'Oficina Interna', 'Troca de escovas', 'João Santos', NOW() - INTERVAL '1 day'),
  (gen_random_uuid()::text, 'a_lap_2', true, NOW() - INTERVAL '5 days', 'Reparado', 200.00, 'Dell Assistência', 'Troca de teclado', 'Maria Admin', NOW() - INTERVAL '15 days'),
  (gen_random_uuid()::text, 'a_ser_3', false, NOW() + INTERVAL '3 days', 'Danificado com chance de reparo', 250.00, 'Oficina Interna', 'Troca de rolamento', 'Carlos Silva', NOW() - INTERVAL '2 days'),
  (gen_random_uuid()::text, 'a_fur_5', true, NOW() + INTERVAL '14 days', 'Itens com reparo alto', 300.00, 'Assistência Externa', 'Rebobinamento', 'Carlos Silva', NOW() - INTERVAL '4 days'),
  (gen_random_uuid()::text, 'a_lap_4', false, NOW() + INTERVAL '2 days', 'Itens com reparo baixo', 80.00, 'TI Interna', 'Formatação', 'Maria Admin', NOW() - INTERVAL '1 day')
  ON CONFLICT (asset_id) DO NOTHING;

  -- 6. History
  INSERT INTO history (id, asset_id, origin_responsible, destination_responsible, quantity, timestamp, type, description, user_name) VALUES
  ('h_1', 'a_fur_1', 'Estoque Central', 'Manutenção Industrial', 1, NOW() - INTERVAL '30 days', 'allocation', 'Alocação inicial', 'Administrador Master'),
  ('h_2', 'a_lap_1', 'Estoque Central', 'Administrativo', 1, NOW() - INTERVAL '30 days', 'allocation', 'Alocação inicial', 'Administrador Master'),
  ('h_3', 'a_fur_4', 'Manutenção Industrial', 'Assistência Externa', 1, NOW() - INTERVAL '2 days', 'status_change', 'Enviado para reparo', 'Carlos Silva'),
  ('h_4', 'a_cad_2', 'Administrativo', 'Operações Logísticas', 10, NOW() - INTERVAL '10 days', 'transfer', 'Transferência de cadeiras', 'Maria Admin'),
  ('h_5', 'a_lap_8', 'Administrativo', 'Dell Assistência', 1, NOW() - INTERVAL '5 days', 'status_change', 'Enviado para manutenção', 'Maria Admin')
  ON CONFLICT (id) DO NOTHING;

  -- 7. Transfers
  INSERT INTO transfers (id, inventory_id, from_team_id, to_team_id, initiated_by, initiated_at, status, completed_at, completed_by) VALUES
  ('tr_1', 'a_fur_3', team_manutencao_id, team_logistica_id, 'Carlos Silva', NOW() - INTERVAL '1 day', 'pending', null, null),
  ('tr_2', 'a_lap_5', team_admin_id, team_manutencao_id, 'Maria Admin', NOW() - INTERVAL '5 days', 'completed', NOW() - INTERVAL '4 days', 'Carlos Silva'),
  ('tr_3', 'a_mon_3', team_admin_id, team_logistica_id, 'Maria Admin', NOW() - INTERVAL '2 days', 'pending', null, null)
  ON CONFLICT (id) DO NOTHING;

  -- 8. Checklists
  INSERT INTO checklists (id, team_id, date, leader_name, discrepancies) VALUES
  ('chk_1', team_manutencao_id, NOW() - INTERVAL '7 days', 'Carlos Silva', 2),
  ('chk_2', team_admin_id, NOW() - INTERVAL '14 days', 'Maria Admin', 0),
  ('chk_3', team_logistica_id, NOW() - INTERVAL '3 days', 'Roberto Almeida', 1)
  ON CONFLICT (id) DO NOTHING;

END $$;
